apiVersion: apps/v1
kind: Deployment  #Kubernetest resource kind we are creating
metadata:
  name: spring-boot-k8s
  labels:
    app: spring-boot-k8s
spec:
  replicas: 3  # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: spring-boot-k8s:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1